
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: warn

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 200

limits_config:
  retention_period: 30d
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_query_series: 10000
  max_query_lookback: 720h
  max_entries_limit_per_query: 100000
  per_stream_rate_limit: "32MB"
  per_stream_rate_limit_burst: "64MB"

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: filesystem

ingester:
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_retain_period: 1m
